title = "Toad OCR"
baseURL = "http://vjp.suvvm.work"
# languageCode = "en-us"
theme = "hugo-theme-techdoc"
#themesDir = "../.."
#resourceDir = "../resources"

#DefaultContentLanguage = "en-us"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

hasCJKLanguage = true
metaDataFormat = "yaml"

defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


[params]

    # Source Code repository section
    description = "Go语言开发的神经网络OCR - 开放RPC接口供开发者使用 - 这是提供介绍和教程的网站"
    github_repository = "https://github.com/suvvm/ToadOCRDocument"
    # version = "0.9.7"

    # Documentation repository section
    # documentation repository (set edit link to documentation repository)
    github_doc_repository = "https://github.com/suvvm/ToadOCRDocument"

    # Analytic section
    # google_analytics_id = "" # Your Google Analytics tracking id
    # tag_manager_container_id = "" # Your Google Tag Manager container id
    # google_site_verification = "" # Your Google Site Verification for Search Console

    # Open Graph and Twitter Cards settings section
    # Open Graph settings for each page are set on the front matter.
    # See https://gohugo.io/templates/internal/#open-graph
    # See https://gohugo.io/templates/internal/#twitter-cards
    title = "Hugo Techdoc Theme"
    images = ["images/og-image.png"] # Open graph images are placed in `static/images`

    # Theme settings section
    # Theme color
    # See color value reference https://developer.mozilla.org/en-US/docs/Web/CSS/color
    custom_font_color = ""
    custom_background_color = ""

    # Documentation Menu section
    # Menu style settings
    menu_style = "open-menu" # "open-menu" or "slide-menu" or "" blank is as no sidebar

    # Date format
    dateformat = "" # default "2 Jan 2006"
    # See the format reference https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference

    # path name excluded from documentation menu
    # menu_exclusion = [
    #     "archives",
    #     "archive",
    #     "blog",
    #     "entry",
    #     "post",
    #     "posts",
    # ]

    # Algolia site search section
    # See https://www.algolia.com/doc/
    # algolia_search_enable = true
    # algolia_indexName = "hugo-demo-techdoc"
    # algolia_appId = "7W4SAN4PLK"
    # algolia_apiKey = "cbf12a63ff72d9c5dc0c10c195cf9128" # Search-Only API Key




# [languages]
#   [languages.en]
#     title = "Toad OCR"
#     weight = 1
#     contentDir = "content/en"
#   [languages.fr]
#     title = "Mon blogue"
#     weight = 2
#     contentDir = "content/fr"


# [sitemap]
#   changefreq = "monthly"
#   priority = 0.5
#   filename = "sitemap.xml"

# [params]
#   favicon = ""
#   site_logo = ""
#   description = "Go语言开发的卷积神经网络OCR - 开放RPC接口供开发者使用 - 这是提供介绍和教程的网站"
#   facebook = ""
#   twitter = "https://twitter.com/suvvm1"
#   instagram = ""
#   youtube = ""
#   github = "https://github.com/suvvm/ToadOCRDocument"
#   gitlab = ""
#   linkedin = ""
#   mastodon = ""
#   slack = ""
#   stackoverflow = ""
#   rss = ""
#   # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
#   background_color_class = "bg-black"
#   featured_image = "/images/gohugo-default-sample-hero-image.jpg"
#   recent_posts_number = 2
